version: "3.6"

services:
  stockprice-service1:
    image: stockprice-service
    container_name: stockprice-service1
    environment: 
      - HTTP_SERVER_PORT=9101
    network_mode: host

  stockprice-service2:
    image: stockprice-service
    container_name: stockprice-service2
    environment: 
      - HTTP_SERVER_PORT=9102
    network_mode: host

  trading-service:
    image: trading-service
    container_name: trading-service
    network_mode: host