db:
  server:
    host: "0.0.0.0"
    port: 5432
  dbName: stockprice
  user: postgres
  password: pass

client:
  stockPrice:
    server:
      host: "0.0.0.0"
      port: 9000
    baseUrl: /api/company/real-time-price

zeebe:
  server:
    host: "0.0.0.0"
    port: 26500

http:
  server:
    host: "0.0.0.0"
    port: 9100

app:
  default:
    pageOffset: 0
    pageLimit: 10