server:
    port: 9100

db:
    host: localhost
    port: 5432
    dbName: stockprice
    user: postgres
    password: pass

client:
    stockPriceBaseUrl: http://localhost:9000/api/company/real-time-price

app:
    default:
        pageOffset: 0
        pageLimit: 10