db:
  server:
    host: "0.0.0.0"
    port: 5432
  dbName: trading
  user: postgres
  password: pass

client:
  stockPrice:
    server:
      host: "0.0.0.0"
      port: 9000

zeebe:
  server:
    host: "0.0.0.0"
    port: 26500

http:
  server:
    host: "0.0.0.0"
    port: 9200
