db:
  server:
    host: "0.0.0.0"
    port: 5432
  dbName: trading
  user: postgres
  password: pass

zeebe:
  server:
    host: "0.0.0.0"
    port: 26500

http:
  server:
    host: "0.0.0.0"
    port: 9200
